name = "tupler"
version = "1.0.0"

description = "Use constructors directly with tuples"
licences = ["MIT"]
repository = { type = "github", user = "MoeDevelops", repo = "tupler" }
links = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
